name: Tag Docker Image on Release

on:
    release:
        types: [published]

jobs:
  tag-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Tag image with release version
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.event.release.tag_name }}

      - name: Push release tag
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.event.release.tag_name }}
